config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :questions do
    resources :answers, only: %i[create]
    collection do
      get 'myquestions'
    end
  end

  resources :memos

  resources :rooms, only: %i[show] do
    resources :comments, only: %i[create]
  end

  resources :comments do
    resource :reactions, only: %i[create destroy]
  end

  root 'memos#index'

  namespace :admins do
    resources :rooms, only: %i[index new edit create update destroy]
    resources :users, only: %i[index edit update destroy]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :name, presence: true, length: { maximum: 20 }
  scope :default_order, -> { order(created_at: :desc) }
end

app/controllers/admins/rooms_controller.rb
class Admins::RoomsController < Admins::ApplicationController
  before_action :set_room, only: %i[show edit update destroy]

  def index
    @rooms = Room.default_order
  end

  def new
    @room = Room.new
  end

  def edit; end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:notice] = 'スレッドが作成されました'
      redirect_to admins_rooms_path
    else
      flash.now[:alert] = 'もう一度入力してください'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @room.update(room_params)
      flash[:notice] = 'スレッドが更新されました'
      redirect_to admins_rooms_path
    else
      flash.now[:alert] = 'もう一度入力してください'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @room.destroy!
    flash[:notice] = 'スレッドを削除しました'
    redirect_to admins_rooms_path
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show]
  def show
    @room = Room.find(params[:id])
    @comment = Comment.new
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admins/rooms/edit.html.erb
<% content_for(:title, "スレッドを作成する") %>

<div class="m-3 mt-5">
  <h2 class="mb-5"><%= @room.name%>を編集</h2>

  <%= simple_form_for [:admins, @room] do |f| %>
    <%= f.input :name, required: false %>
    <div class="text-center">
       <%= f.button :submit, '更新する', class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admins/rooms/index.html.erb
<% content_for(:title, "スレッド一覧") %>

<div class="m-3 mt-5">
  <h2>スレッド一覧</h2>
  <div class="text-end">
    <%= link_to 'スレッドを作成する', new_admins_room_path, class: "btn btn-primary"%>
  </div>
  
  <% if @rooms.present? %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">スレッド名</th>
          <th scope="col">作成日時</th>
          <th scope="col"></th>
        </tr>
      </thead>
  　  <% @rooms.each do |room| %>
        <tbody>
          <tr>
            <td><%= room.name %></td>
            <td><%= l room.created_at, format: :short %></td>
            <td class="d-flex justify-content-evenly">
              <%= link_to edit_admins_room_path(room), class: "btn btn-success" do %>
                編集 <i class="fa-solid fa-pen-to-square"></i>
              <% end %>
              <%= button_to admins_room_path(room), data: { confirm: "本当に削除しますか?", turbo_confirm: "本当に削除しますか?" }, method: :delete, class: "btn btn-danger" do %>
                削除 <i class="fa-solid fa-trash-can"></i>
              <% end %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  <% else %>
    現在スレッドはありません
  <% end %>
</div>

app/views/admins/rooms/new.html.erb
<% content_for(:title, "スレッドを作成する") %>

<div class="m-3 mt-5">
  <h2 class="mb-5">スレッドを作成する</h2>

  <div class="pt-5">
    <%= simple_form_for [:admins, @room] do |f| %>
      <div class="field col-md-6 offset-md-3">
        <%= f.input :name, required: false %>
      </div>
      <div class="text-center">
         <%= f.button :submit, '作成する', class: "btn btn-success mt-4" %>
      </div>
    <% end %>
  </div>
</div>