config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :questions do
    resources :answers, only: %i[create]
    collection do
      get 'myquestions'
    end
  end

  resources :memos

  resources :rooms, only: %i[show] do
    resources :comments, only: %i[create]
  end

  resources :comments do
    resource :reactions, only: %i[create destroy]
  end

  root 'memos#index'

  namespace :admins do
    resources :rooms, only: %i[index new edit create update destroy]
    resources :users, only: %i[index edit update destroy]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :memos, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 20 }

  mount_uploader :image, ImageUploader # 画像のアップロード用

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    resultbb
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::ApplicationController
  before_action :set_user, only: %i[edit update destroy]
  # ApplicationContorollerに before_action :authenticate_admin! がすでに記述してある。

  def index
    @users = User.all
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'プロフィールが更新されました'
      redirect_to admins_users_path
    else
      flash.now[:alert] = 'もう一度入力してください'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy!
    flash[:notice] = 'ユーザーを削除しました'
    redirect_to admins_users_path
  end

  private

  # @userの中身を定義
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]

  private

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name image])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admins/users/edit.html.erb
<h2 class="mb-5 mt-5"><%= @user.name%>を編集</h2>
<%= simple_form_for(@user, url: admins_user_path) do |f| %>
  <%= f.input :name, required: false%>
  <%= f.input :email, required: false%>
  <div class="text-center mt-5">
    <%= f.button :submit, '保存する', class: "btn btn-success"%>
  </div>
<% end %>

app/views/admins/users/index.html.erb
<% content_for(:title, "アカウント一覧") %>

<div class="m-3 mt-5">
  <h2>アカウント一覧</h2>
  
  <% if @users.present? %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">アカウント名</th>
          <th scope="col">メールアドレス</th>
          <th scope="col"></th>
        </tr>
      </thead>
  　  <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email%></td>
            <td class="d-flex justify-content-evenly">
              <%= link_to edit_admins_user_path(user), class: "btn btn-success" do %>
                編集 <i class="fa-solid fa-pen-to-square"></i>
              <% end %>
              <%= button_to admins_user_path(user), data: { confirm: "本当に削除しますか?", turbo_confirm: "本当に削除しますか?" }, method: :delete, class: "btn btn-danger" do %>
                削除 <i class="fa-solid fa-trash-can"></i>
              <% end %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  <% else %>
    現在アカウントは登録されていません
  <% end %>
</div>