config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :questions do
    resources :answers, only: %i[create]
    collection do
      get 'myquestions'
    end
  end

  resources :memos

  resources :rooms, only: %i[show] do
    resources :comments, only: %i[create]
  end

  resources :comments do
    resource :reactions, only: %i[create destroy]
  end

  root 'memos#index'

  namespace :admins do
    resources :rooms, only: %i[index new edit create update destroy]
    resources :users, only: %i[index edit update destroy]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  include BadWordsFilter
  belongs_to :question
  validates :description, presence: true
  before_save :set_filtered_bad_answer

  scope :default_order, -> { order(created_at: :desc) }

  private

  def set_filtered_bad_answer
    self.description = filter_bad_words(description)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include BadWordsFilter
  belongs_to :user
  belongs_to :room
  has_many :reactions, dependent: :destroy
  before_save :set_filtered_bad_comment
  validates :content, presence: true, length: { maximum: 200 }

  def user_name
    user.name
  end

  def reacted_by?(user)
    reactions.exists?(user_id: user.id)
  end

  private

  def set_filtered_bad_commment
    self.content = filter_bad_words(content)
  end
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 50 }

  scope :default_order, -> { order(created_at: :desc) }
end

app/models/question.rb
class Question < ApplicationRecord
  include BadWordsFilter
  belongs_to :user
  has_many :answers, dependent: :destroy
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true
  before_save :set_filtered_bad_description
  scope :default_order, -> { order(created_at: :desc) }
  attr_accessor :qiita_articles

  def search_qiita_and_associate
    qiita_search_results = search_qiita(title)
    associate_qiita_results(qiita_search_results)
  end

  private

  def search_qiita(query)
    qiita_api_endpoint = 'https://qiita.com/api/v2/items'
    api_token = ENV['QIITA_API_TOKEN']
    uri = URI(qiita_api_endpoint)
    params = { 'query' => query }
    uri.query = URI.encode_www_form(params)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Get.new(uri.request_uri)
    request['Authorization'] = "Bearer #{api_token}"
    response = http.request(request)
    if response.is_a?(Net::HTTPSuccess)
      JSON.parse(response.body)
    else
      []
    end
  end

  def associate_qiita_results(qiita_results)
    qiita_articles = []
    qiita_results.each do |qiita_result|
      qiita_article = {
        title: qiita_result['title'],
        url: qiita_result['url']
      }
      qiita_articles << qiita_article
    end
    self.qiita_articles = qiita_articles
  end

  def set_filtered_bad_description
    self.title = filter_bad_words(title)
    self.description = filter_bad_words(description)
  end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :name, presence: true, length: { maximum: 20 }
  scope :default_order, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :memos, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 20 }

  mount_uploader :image, ImageUploader # 画像のアップロード用

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    resultbb
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: %i[show edit update destroy]

  def index
    @memos = current_user.memos.default_order.page(params[:page])
  end

  def show; end

  def new
    @memo = current_user.memos.new
  end

  def edit; end

  def create
    @memo = current_user.memos.new(memo_params)
    if @memo.save
      flash[:notice] = 'メモが追加されました'
      redirect_to memo_path(@memo)
    else
      flash.now[:alert] = 'もう一度入力してください'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @memo.update(memo_params)
      flash[:notice] = 'メモが更新されました'
      redirect_to memo_path(@memo)
    else
      flash.now[:alert] = 'もう一度入力してください'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @memo.destroy!
    flash[:notice] = 'メモを削除しました'
    redirect_to memos_path
  end

  private

  def set_memo
    @memo = current_user.memos.find(params[:id])
  end

  def memo_params
    params.require(:memo).permit(:title, :description)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show]
  def show
    @room = Room.find(params[:id])
    @comment = Comment.new
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    base_title = '🌈 メモトーーク！'
    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def admin_page_title(page_title = '')
    base_title = '🌈【管理者画面】メモトーーク！'
    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def should_hide_pagination?(obj)
    obj.total_pages > 1 && obj.count < 5
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/markdown_helper.rb
class CustomRenderHTML < Redcarpet::Render::HTML
end

module MarkdownHelper
  def plaintext(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::StripDown)
    markdown.render(text)
  end

  def markdown(text)
    options = {
      with_toc_data: true,
      hard_wrap: true
    }
    extensions = {
      no_intra_emphasis: true,
      tables: true,
      autolink: true,
      lax_spacing: true,

      lax_html_blocks: true,
      footnotes: true,
      space_after_headers: true,
      strikethrough: true,
      underline: true,
      highlight: true,
      quote: true
    }

    renderer = CustomRenderHTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end

  def toc(text)
    renderer = Redcarpet::Render::HTML_TOC.new(nesting_level: 6)
    markdown = Redcarpet::Markdown.new(renderer)
    markdown.render(text).html_safe
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_before_login_sidebar.html.erb
<div class="d-flex flex-column p-3 text-white bg-dark sidebar__content">
  <%= link_to "🌈メモトーーク!", new_user_session_path, class: "fs-4 d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none"%>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= link_to new_user_session_path, class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-solid fa-right-to-bracket"></i> ログイン
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_user_registration_path, class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-solid fa-user-plus"></i> サインアップ
      <% end %>
    </li>
    <li>
      <%= link_to questions_path, class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-solid fa-file-circle-question"></i> 質問掲示板
      <% end %>
    </li>
    <hr>
    <li class="nav-item fw-bold thread_index">
      <i class="fa-solid fa-rainbow"></i> スレッド一覧
    </li>
    <br>
    <div class="before_loggin_thred_scroll">
      <% rooms = Room.all %>
      <% if rooms.present? %>
        <% rooms.each do |room| %>
          <li>
            <%= link_to room.name, room_path(room), class: "nav-link fw-bold sidebar__link"%>
          </li>
        <% end %>
      <% end %>
    </div>
  </ul>
</div>

app/views/layouts/_notification.html.erb
<% if flash.present? %>
  <% flash.each do |key, value| %>
   <%= content_tag :div, value, class: key %>
  <% end %>
<% end %>

app/views/layouts/_open_sidebar.html.erb
<div class="d-flex flex-column p-3 text-white bg-dark sidebar__content">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
    <span class="ml-3 fs-4">🌈メモトーーク!</span>
  </a>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= link_to "ログイン", new_session_path(resource_name), class: "nav-link fw-bold sidebar__link"%>
    </li>
    <li class="nav-item">
      <%= link_to "サインアップ", new_registration_path(resource_name), class: "nav-link fw-bold sidebar__link"%>
    </li>
  </ul>
</div>

app/views/layouts/_pagination.html.erb
<div class="pagination justify-content-start p-3">
  <%= paginate obj, theme: 'bootstrap-5' %>
</div>

app/views/layouts/_reactions.html.erb
<% if @comment.reacted_by?(current_user) %>
  <%= link_to comment_reactions_path(@comment), data: { "turbo-method": :delete }, class: "liked" do %>
    <i class="fas fa-heart"></i>
    <%= @comment.reactions.count %>
  <% end %>
<% else %>
  <%= button_to comment_reactions_path(@comment), data: { "turbo-method": :post }, class: "unliked" do %>
    <i class="fas fa-heart"></i>
    <%= @comment.reactions.count %>
  <% end %>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="d-flex flex-column p-3 text-white bg-dark sidebar__content">
  <%= link_to "🌈メモトーーク!", root_path, class: "fs-4 d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none"%>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= link_to memos_path, class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-solid fa-book-open"></i> メモ一覧
      <% end %>
    </li>
    <li>
      <%= link_to new_memo_path, class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-solid fa-circle-plus"></i> メモ新規追加
      <% end %>
    </li>
    <li>
      <%= link_to questions_path, class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-solid fa-file-circle-question"></i> 質問掲示板
      <% end %>
    </li>
    <li>
      <%= link_to myquestions_questions_path, class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-solid fa-person-circle-question"></i> 自分の質問
      <% end %>
    </li>
    <li>
      <%= link_to new_question_path, class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-regular fa-comments"></i> 質問する
      <% end %>
    </li>
    <hr>
    <li class="nav-item fw-bold thread_index">
      <i class="fa-solid fa-rainbow"></i> スレッド一覧
    </li>
    <br>
    <div class="scroll">
    <% rooms = Room.all %>
    <% if rooms.present? %>
      <% rooms.each do |room| %>
        <li>
          <%= link_to room.name, room_path(room), class: "nav-link fw-bold sidebar__link"%>
        </li>
      <% end %>
    <% end %>
    </div>
  </ul>
  <hr>
  <div class="dropdown">

    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">

      <% if current_user.image? %>
        <%= image_tag current_user.image.url, size: '32x32', class: 'rounded-circle me-2' %>
      <% else %>
        <%= image_tag 'default.png', size: '32x32', class: 'rounded-circle me-2' %>
      <% end %>

      <strong><%= current_user.name %></strong>
    </a>

    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
      <li>
        <%= link_to edit_user_registration_path, class:"dropdown-item" do%>
          <i class="fa-regular fa-user"></i> プロフィール
        <% end %>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <%= button_to destroy_user_session_path, method: :delete, class:"dropdown-item" do %>
          <i class="fa-solid fa-right-from-bracket"></i> ログアウト
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/admin/_before_login_sidebar.html.erb
<div class="d-flex flex-column p-3 text-white bg-secondary sidebar__content">
  <%= link_to "🌈 【管理者画面】メモトーーク!", new_session_path(resource_name), class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none"%>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= link_to new_session_path(resource_name), class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-solid fa-right-to-bracket"></i> ログイン
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/admin/_sidebar.html.erb
<div class="d-flex flex-column p-3 text-white bg-secondary sidebar__content">
  <%= link_to "🌈 【管理者画面】メモトーーク!", "#", class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none"%>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= link_to admins_rooms_path, class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-brands fa-buromobelexperte"></i> スレッド一覧
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to admins_users_path, class: "nav-link fw-bold sidebar__link" do %>
        <i class="fa-solid fa-people-line"></i> アカウント一覧
      <% end %>
    </li>
  </ul>
  <hr>
  <div class="dropdown admin__sidebar-dropdown">
    
    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
      <strong><%= current_admin.email %></strong>
    </a>
    
    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
      <li>
        <%= link_to edit_admin_registration_path, class:"dropdown-item" do %>
          <i class="fa-regular fa-user"></i> 設定
        <% end %>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <%= button_to destroy_admin_session_path, method: :delete, class:"dropdown-item" do %>
          <i class="fa-solid fa-right-from-bracket"></i> ログアウト
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= admin_page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/notification' %>

    <% if admin_signed_in? %>
      <div class="row">
        <div class="col-3">
          <%= render "layouts/admin/sidebar"%>
        </div>
         <div class="col-8">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="col-3">
          <%= render "layouts/admin/before_login_sidebar"%>
        </div>
         <div class="col-8">
          <%= yield %>
        </div>
      </div>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/notification' %>

    <% if user_signed_in? %>
      <div class="row">
        <div class="col-3">
          <%= render "layouts/sidebar"%>
        </div>
        <div class="col-8">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="col-3">
          <%= render "layouts/before_login_sidebar"%>
        </div>
        <div class="col-8">
          <%= yield %>
        </div>
      </div>
    <% end %>
  </body>
</html>