config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :questions do
    resources :answers, only: %i[create]
    collection do
      get 'myquestions'
    end
  end

  resources :memos

  resources :rooms, only: %i[show] do
    resources :comments, only: %i[create]
  end

  resources :comments do
    resource :reactions, only: %i[create destroy]
  end

  root 'memos#index'

  namespace :admins do
    resources :rooms, only: %i[index new edit create update destroy]
    resources :users, only: %i[index edit update destroy]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 50 }

  scope :default_order, -> { order(created_at: :desc) }
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: %i[show edit update destroy]

  def index
    @memos = current_user.memos.default_order.page(params[:page])
  end

  def show; end

  def new
    @memo = current_user.memos.new
  end

  def edit; end

  def create
    @memo = current_user.memos.new(memo_params)
    if @memo.save
      flash[:notice] = 'メモが追加されました'
      redirect_to memo_path(@memo)
    else
      flash.now[:alert] = 'もう一度入力してください'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @memo.update(memo_params)
      flash[:notice] = 'メモが更新されました'
      redirect_to memo_path(@memo)
    else
      flash.now[:alert] = 'もう一度入力してください'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @memo.destroy!
    flash[:notice] = 'メモを削除しました'
    redirect_to memos_path
  end

  private

  def set_memo
    @memo = current_user.memos.find(params[:id])
  end

  def memo_params
    params.require(:memo).permit(:title, :description)
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<%= simple_form_for(@memo, url: url) do |f| %>
  <%= f.input :title, required: false%>
  <%= f.input :description, as: :text, input_html: { rows: 18 }, placeholder: "マークダウンが使用可能です"%>
  <div class="text-center mt-5">
    <%= f.button :submit, '保存する', class: "btn btn-success"%>
  </div>
<% end %>

app/views/memos/edit.html.erb
<% content_for(:title, "メモ編集") %>

<div class="m-3 mt-5">
  <h2 class="mb-5"><%= @memo.title%></h2>
  <div class="text-end show_time">
    更新日時: <%= l @memo.updated_at, format: :short %>
  </div>
  <%= render 'form', url: memo_path(@memo)%>
</div>

app/views/memos/index.html.erb
<% content_for(:title, "メモ一覧") %>

<div class="m-3 mt-5">
  <h2>メモ一覧</h2>
  <div class="text-end">
    <%= link_to 'メモ新規追加', new_memo_path, class: "btn btn-primary"%>
  </div>

  <%= render "layouts/pagination", obj: @memos%>

  <% if @memos.present? %>
  　<% @memos.each do |memo| %>
  　<div class="card mr-5 ms-5">
      <div class="card-body">
  　    <%= link_to memo_path(memo), class: "memo_title" do %>
  　      <%= memo.title %>
  　      <div class="text-muted small text-truncate">
  　        <%= memo.description%>
  　      </div>
　      <% end %>
　     <div class="d-flex float-end">
    　    <%= link_to "編集", edit_memo_path(memo), class: "btn btn-success" %>
    　    <%= button_to "削除", memo_path(memo), data: { confirm: "本当に削除しますか?", turbo_confirm: "本当に削除しますか?" }, method: :delete, class: "btn btn-danger"%>
　     </div>
  　   </div>
　     <div class="text-end memo_time">
        <%= l memo.updated_at, format: :short %>
      </div>
  　</div>
    <% end %>
  <% else %>
    メモを追加しましょう！
  <% end %>
</div>

<% unless should_hide_pagination?(@memos) %>
  <!-- メモの件数が少ない場合、下部にもページネーションが登場して不恰好になってしまう。そのため件数が少ない場合には下部のページネーションは非表示にする。 -->
  <div class="mt-5">
    <%= render "layouts/pagination", obj: @memos %>
  </div>
<% end %>

app/views/memos/new.html.erb
<% content_for(:title, "メモ追加") %>

<div class="m-3 mt-5">
  <h2 class="mb-5">メモ新規登録</h2>
  <%= render 'form', url: memos_path(@memo)%>
</div>

app/views/memos/show.html.erb
<% content_for(:title, @memo.title ) %>
<div class="m-3 mt-5">
  <h2><%= @memo.title%></h2>
  <div class="text-end show_time">
    更新日時: <%= l @memo.updated_at, format: :short %>
  </div>
  <div class="card mt-5">
    <div class="card-header">
      <div class="d-flex justify-content-end gap-2">
        <%= link_to '編集', edit_memo_path(@memo), class: "btn btn-success"%>
        <%= button_to '削除', memo_path(@memo), data: { confirm: "本当に削除しますか?", turbo_confirm: "本当に削除しますか?"},  method: :delete, class: "btn btn-danger"%>
      </div>
    </div>
    <div class="card-body">
      <%= markdown(@memo.description)%>
    </div>
  </div>
</div>